# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

#create a volume for the  mssql container.To ensure Data persists after mssql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    #Pull the latest mssql image
    image: mcr.microsoft.com/mssql/server:2022-latest
    #Map port 1433 on the mssql container to port 1433 in the host
    ports:
      - "1433:1433"
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/opt/mssql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    #Specify Environment Variables for mssql
    environment: 
      MSSQL_SA_PASSWORD: Qwerty@12345
      MSSQL_USER: SA
      MSSQL_DATABASE: Foodsdb
      MSSQL_PID: "Developer"
      ACCEPT_EULA: Y
        #Api  Service
  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "5000:80"
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development